spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter

listeningQueue:
    json: JsonDeviceMsgQueue
    byte: ByteDeviceMsgQueue
server:
  port: 8080
