spring:
  rabbitmq:
    host: 39.106.168.77
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter

listeningQueue:
    json: JsonDeviceMsgQueue
    byte: ByteDeviceMsgQueue

server:
  port: 8081
